# Site
repository: toddcolsen/toddcolsen.github.io
favicon: images/favicon.ico


# Content configuration version
version: 2


# Dark Mode (true/false/never)
darkmode: true

# Personal info
title: Data Scientist & Engineer
description: My Personal Page on GitHub
name : Todd Olsen
email: olsentoddc@gmail.com
website: https://toddcolsen.github.io

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: todd-olsen-91515312
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  My name is Todd Olsen and I'm a Data Scientist / Data Engineer.  I most recently worked for the Volvo Group at their plant in Hagerstown, 
  MD, where I processed and analyzed data from diesel engines.

    
  
  



content:             

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: MS Computer Science
        caption: University of Maryland Baltimore County (UMBC)
        sub_title: #MSc Computer Science
        description: | # this will include new lines to allow paragraphs
           I got my Masters degree in Computer Science from UMBC.  My focus was on `Machine Learning` and I was part of the DIADIC (DIstributed Adaptive Discovery and Computation) group headed by Dr. Hillol Kargupta.  My thesis "Distributed Decision Tree Learning From Multiple Heterogeneous Data Sources".
           
      - layout: left
        title: BS Physics
        caption: Case Western Reserve University (CWRU)
        sub_title: #BS Physics
        description: | # this will include new lines to allow paragraphs
          I got my Bachelors degree in Physics from CWRU.  I worked in the lab of [Prof. Rolfe G. Petschek](https://physics.case.edu/emeriti/rolfe-g-petschek/), where I worked on the spontaneous alignment of farroelectric liquid crystal inside containers.
          

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Professional Data Engineer
        link: volvogroup.com
        # link_text: volvogroup.com
        sub_title: Volvo Group
        caption: Hagerstown, MD
        quote: > 
            
        description: | # this will include new lines to allow paragraphs
            I performed both data science and data engineering roles in support of engine testing.  
            
            
      - layout: left
        title: Data Scientist
        link: https://www.komatsu.com/en-za/industries/underground-soft-rock-mining
        # link_text: boringcompany.com
        sub_title: Komatsu Mining
        caption: Warrendale, PA
        quote: > 
            
        description: | # this will include new lines to allow paragraphs
            Data Scientist in support of predictive analytics for mining machinery.  
            
            
        - layout: left
        title: Research Statistician
        link: vistaprint.com
        # link_text: boringcompany.com
        sub_title: Webs.com
        caption: Silver Spring, MD
        quote: > 
            
        description: | # this will include new lines to allow paragraphs
            A data science role for a small web company in Silver Spring.  Webs was acquired and absored by VistaPrint.
            
            
        - layout: left
        title: Statistician
        link: claritas.com
        # link_text: boringcompany.com
        sub_title: Claritas
        caption: Arlington, VA
        quote: > 
            
        description: | # this will include new lines to allow paragraphs
            I built models of consumer purchasing behavior by demographic group.



  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:         
      - layout: top-middle
        title: Data Analysis of the Indus Script
        link: https://github.com/toddcolsen/indus_script
        link_text: GitHub Project
        additional_links:
          - title:  Github page
            icon: fab fa-github
            url: https://github.com/toddcolsen/indus_script
        quote:  
        description: | # this will include new lines to allow paragraphs           
           *This project contains code and data for my analysis of the Indus Script (aka. the Harrapan Script).*
          
          
      - layout: top-middle
        title: PokerBuddy
        link: 
        # link_text: Project Website
        additional_links:
          - title:  Github page
            icon: fab fa-github
            url: 
        quote: >
          X
        description: | # this will include new lines to allow paragraphs
          X
      
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:   

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme #(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-include-cache

